name: ptt_mobile
description: Push-to-Talk Mobile Application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP and WebSocket
  http: ^1.1.0
  socket_io_client: ^2.0.3+1
  
  # Audio recording and playback
  record: ^5.0.4
  audioplayers: ^5.2.1
  permission_handler: ^11.0.1
  
  # State management
  provider: ^6.1.1
  
  # Storage
  shared_preferences: ^2.2.2
  
  # UI
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  
  # Utils
  intl: ^0.18.1
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
